global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "traffic-api"
    static_configs:
      - tragets: ["traffic-api:8000"]

  - job_name: "anomaly-service"
    static_configs:
      - tragets: ["anomaly-service:8001"]
    